name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    # -------- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    name: Build distribution 📦
    runs-on: ubuntu-20.04

    steps:
      # -------- https://github.com/actions/checkout
      # check out your repository files onto the runner, so that the workflow can access them
      - uses: actions/checkout@v4

      # -------- https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.6"

      # --------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          pip install -r requirements.txt

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install pangocairo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libcairo2-dev

      # --------
      - name: Format with black
        run: |
          black . --line-length=128
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.py'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Formatted code with black."
          default_author: github_actor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest
        run: pytest _test.py

      # -------- build --------
      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build a binary wheel and a source tarball]
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  # -------- pypi --------
  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs:
    - build
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/Tensor-Spectacle
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  # -------- testpypi --------
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-20.04

    environment:
      name: testpypi
      url: https://pypi.org/p/Tensor-Spectacle

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/